Add export functions
coavins/mhrise-coavins-dps pull request #52
Opened 2022-10-12 13:14 UTC by nisemaru

Hi coavins. 
I am sorry to be late.
Previously, I sent a message on nexusmods.
Please check and merge the Export feature!!

My WebSite is made with this export function.
https://bonjin-hunter-db.com/

2022-10-21 15:00 UTC, coavins requested changes
There are some small changes that I think should be made, but otherwise this looks good. Let me know what you think about my suggestions, and I will merge when you're ready.

2022-10-26 13:59 UTC, nisemaru commented on src/autorun/mhrise-coavins-dps.lua
> +		CORE.getWeaponInfo()
I agree. I have confirmed that there is no problem with the above operation.

2022-10-26 14:01 UTC, nisemaru commented on src/autorun/mhrise-coavins-dps/export.lua
> +this.round = function(x, n)
I forgot to delete it, so please remove `n`.

2022-11-13 16:37 UTC, coavins approved these changes
Looks good, sorry for the delay on this. I will go ahead with the merge now.

2022-11-13 16:39 UTC, merged

2022-11-13 17:12 UTC, coavins commented
I have posted version 2.12 to Nexus mods which includes these changes.